name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm install

      - run: npm run build

      - name: Update .env File
        run: |
          cd /home/souheib/actions-runner/_work/social-media-client/social-media-client/dist
          echo "VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}" > .env
          echo "VITE_SOCKET_URL=${{ secrets.VITE_SOCKET_URL }}" >> .env
