name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm install

      - run: npm run build

      - name: Deploy via SSH and Update .env
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          script: |
            cd /home/azureuser/actions-runner/_work/social-media-client/social-media-client/dist
            # Create or update the .env file with GitHub secrets
            echo "VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}" > .env
            echo "VITE_SOCKET_URL=${{ secrets.VITE_SOCKET_URL }}" >> .env
            # If using npm start or another command to start the server:
            npm start
